name: dotnet pack and publish

on:
  release:
    types: [released]
    branches: [ main ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -warnaserror --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: version=${GITHUB_REF##*/} dotnet pack -c Release
